- XIVSlothCombo/CustomCombo/Functions/Config.cs
- XIVSlothCombo/Data/ContentCheck.cs
- XIVSlothCombo/Window/Functions/UserConfig.cs
Same as #35.
This adds brand new filtering capabilities based on Content Difficulty with `ContentCheck` and UI elements to add to your settings to add difficulty filtering to your options.
The biggest use-case for this is more restrictive settings in Advanced Mode that don't necessarily make sense for all types of content; for example DRK has options to stop using abilities at set HP% thresholds - these options make way more sense in more casual content. So I can add the `DrawDifficultyMultiChoice` UI element under that HP% slider, hook up `IsInConfiguredContent` in my actual job code and now the setting makes more sense.
There are multiple setups for Content Difficulty filtering called list sets. These are the current values of those list sets - I am very open to feedback on how the …
> [Core] Content difficulty filtering

- XIVSlothCombo/Window/Functions/Presets.cs
- XIVSlothCombo/Window/Tabs/PvEFeatures.cs
- XIVSlothCombo/Window/Tabs/PvPFeatures.cs
> [Core] Keep Option #s consistent

- XIVSlothCombo/Data/ConflictingPluginsCheck.cs
- XIVSlothCombo/Data/RepoCheck.cs
- XIVSlothCombo/Window/ConfigWindow.cs
- XIVSlothCombo/XIVSlothCombo.cs
Same as #6.
This adds reminder text for users about conflicting plugins, and a tooltip advising them to disable the plugins.
It is just a simple check for the most common combo plugins, so it can help every-day users without substantial code to try to account for dev plugins, etc.
Additionally, it adds the conflict count and list of conflicting plugins to debug logs.
<table><tr><td>
```
START DEBUG LOG
Plugin Version: 1.0.0.0
Installation Repo: !! Self-Built !!
Conflicting Plugins: 2
- XIVCombo(1.8.5.0)
- XIVComboExpanded(2.0.0.12)
```
</td><td>
```
START DEBUG LOG
Plugin Version: 1.0.0.0
Installation Repo: !! Self-Built !!
Conflicting Plugins: 0
```
</td></tr></table>
> Additionally, this also includes:
> - A little bit of cleanup for `RepoCheck`
> - Support for grabbing URL from plugins …
> [Core] Conflicting Plugins

- XIVSlothCombo/Combos/PvE/MNK/MNK.cs
GCDs should change when corresponding gauge is empty, independent of current stance or buffs
> [MNK] Beast Chakras improvements

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/ADV/ADV_Config.cs
- XIVSlothCombo/Combos/PvE/ALL/ALL_Config.cs
- XIVSlothCombo/Combos/PvE/BLU/BLU_Config.cs
- XIVSlothCombo/Combos/PvE/DOH/DOH_Config.cs
- XIVSlothCombo/Combos/PvE/DOL/DOL_Config.cs
- XIVSlothCombo/Combos/PvE/SCH/SCH.cs
- SCH Fairy Reminder now includes Summon Seraph. Fixed ReplaceSkill attribute
- Commented out multiple empty config switches to shut up compile warnings
> SCH Fairy Reminder, Warning Squash

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/DNC/DNC.cs
Added Closed position, out of combat, for both st and aoe advanced. Must be in a party/trust or have a Chocobo out. Requires manual target choice.
> [DNC] Dance Partner Reminder

- XIVSlothCombo/Combos/PvE/RDM/RDM.cs
Simply moved lucid below the ogcd section so that it will put damage ogcds ahead of lucid like the other casters. 
Brought up in discord asking about a priority system. Not really needed. But putting lucid below might help the niche case when lucid could get in the way of a damage ogcd
> [RDM] Lucid deprioritize

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/AST/AST_Config.cs
- XIVSlothCombo/Combos/PvE/MCH/MCH_Config.cs
- XIVSlothCombo/Combos/PvE/NIN/NIN_Config.cs
- XIVSlothCombo/Combos/PvP/ASTPVP.cs
- XIVSlothCombo/Combos/PvP/BLMPVP.cs
- XIVSlothCombo/Combos/PvP/BRDPVP.cs
- XIVSlothCombo/Combos/PvP/DRKPVP.cs
- XIVSlothCombo/Combos/PvP/GNBPVP.cs
- XIVSlothCombo/Combos/PvP/MCHPVP.cs
- XIVSlothCombo/Combos/PvP/MNKPVP.cs
- XIVSlothCombo/Combos/PvP/NINPVP.cs
- XIVSlothCombo/Combos/PvP/PCTPVP.cs
- XIVSlothCombo/Combos/PvP/PLDPVP.cs
- XIVSlothCombo/Combos/PvP/PVPCommon.cs
- XIVSlothCombo/Combos/PvP/RDMPVP.cs
- XIVSlothCombo/Combos/PvP/RPRPVP.cs
- XIVSlothCombo/Combos/PvP/SAMPVP.cs
- XIVSlothCombo/Combos/PvP/SCHPVP.cs
- XIVSlothCombo/Combos/PvP/SGEPVP.cs
- XIVSlothCombo/Combos/PvP/SMNPvP.cs
- XIVSlothCombo/Combos/PvP/VPRPVP.cs
- XIVSlothCombo/Combos/PvP/WARPVP.cs
- XIVSlothCombo/Combos/PvP/WHMPVP.cs
7.1 PvP Updates
Updated to reflect the latest changes introduced in patch 7.1 for PvP.
Implemented a check to avoid wasting burst skills on targets that are immune to or cannot take significant damage.
Expanded on the customization options
Added Limit Break (LB) usage in burst mode for select jobs, with plans to expand this functionality further in future updates.
> [PvP] 7.1 PvP update

- XIVSlothCombo/XIVSlothCombo.cs
fix for https://github.com/PunishXIV/WrathCombo/pull/63
the command switch only operates on the first word, not on multiple.
> [Core] `/wrath` auto-rotation enable and disable commands fix

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/BRD/BRD.cs
- XIVSlothCombo/Combos/PvE/MCH/MCH.cs
Added interrupt to AoE Simple and advanced for bard and machinist to match dancer.
I did not touch machinists interrupt in delayed weave only.
Fixes #85 
Fixes #86 
Turned the songs in the ST ogcd feature into an option instead of forced
Added songs to the aoe ogcd Feature to match the st one. 
I ported the cleanup from the other PR from gakai into this one. The dot management is much nicer in ironjaws features. 
Added warden's paeon option to st and aoe for self cleansing cleansable debuffs
added small ast description text change to clarify aspected helios and helios conjuction being the same thing. wasnt worth its own fork
> [BRD & MCH] Aoe Interrupts + Bard changes

- XIVSlothCombo/Combos/PvE/DNC/DNC.cs
> [!NOTE]
> Ideally features are designed to also work in auto-rotation, not ever disabled for auto-rotation.
> In this case it would be better to implement this with default targeting to support auto-rotation, but we do not have the tools currently required to do so in a concise way and do plan to in the near-term.
> [DNC] Prevent new DP option from bricking Auto-Rotation

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
> [GNB] more 7.1 fixes/adjustments

- WrathCombo/Combos/PvE/SMN/SMN.cs
The Demi attack block for ST and AOE did not have weave checks.
Also adjusted the advanced aoe weave check to use actionwatching.lastspell like single target was.
Simply moved the demi attack code block to be within the canspellweave code block for ST and AOE advanced combos.
Simple combo worked fine with no weave issues.
> SMN Weaving fixes for demi attacks.

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
TLDR. Basically a full and final cleaning of bards spaghetti. Inspired by zbees dancer code, set up regions and comments on sections so anyone can quickly read and troubleshoot issues in bard code. Lastly implemented Gakais dot management code across all features that need it as it cuts the section in half. 
Fixed: Added delayed weave to low lvl song toggle to keep it from doubleweaving them together due to speed on autorotation. 
Combo Preset Cleanup and Option ordering, Feature cleanup and organization.
Simple and Advanced Cleanup
> [BRD] Cleanup and organization

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvP/SAMPVP.cs
Samurai is now fully 7.1 tested and supported.
> [PvP] SAM Wrath Update

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
> PCT Opener update + Fix Autorotation issue

- WrathCombo/Core/PluginConfiguration.cs
- WrathCombo/CustomCombo/Functions/Target.cs
- WrathCombo/Window/SettingChangeWindow.cs
- WrathCombo/WrathCombo.cs
> [Core] Update Max Melee range, migrate users to it

- WrathCombo/CustomCombo/Functions/Target.cs
Clamp down return value range from 0f to 100f
Fixes reported SGE Discord issue
> [Core] Added GetTargetHPPercent Limits

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/RPR/RPR_Config.cs
- WrathCombo/Combos/PvP/RPRPVP.cs
> [PVP] RPR Fixes and updates

- WrathCombo/Combos/PvE/BRD/BRD.cs
> [BRD] Fixes

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvP/PVPCommon.cs
Edited the Anti mash feature. 
Original feature prevents you from unguarding by accident in pvp using your combo buttons. It only leaves guard untouched so you can use that to get out of guard. 
The change
If you have the mp AND could use the 15k healing with wasting it, it changes that guard button to recuperate so that can be used to take you out of guard. Exact same functionality, removing guard, but allows you to do it with the heal instead of having to hit guard and then heal resulting in a delay. 
The original request in discord wanted other skills, but to do that, would require unlocking those skills under guard and would likely result in the anti-mash feature having potential fails.
> [PVP] Global Emergency Guard Anti Mash edit

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvP/MNKPVP.cs
> [PVP] [MNK] Riddle of Earth fix and LB option

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG_Config.cs
- WrathCombo/Combos/PvP/DRGPVP.cs
Key note. With elusive lockout the burst combo still functions exactly the same. This is primarily for those who dont want everything they have locked behind using backflip.
> [PVP] [DRG] Update

- WrathCombo/CustomCombo/Functions/Target.cs
> [Core] Account more widely for player hitbox

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Config.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
> [MNK] Various

- WrathCombo/Core/PluginConfiguration.cs
- WrathCombo/Data/ActionWatching.cs
- WrathCombo/WrathCombo.cs
> [Core] Make chat message prefixes more consistent

- WrathCombo/Window/Tabs/AutoRotationTab.cs
(especially useful for removing different levels of target dummies)
- Moves it's hint to be a hint tooltip
- Clarifies the box with a header label instead
> [UI] Make the Ignore List more consistent

- WrathCombo/Combos/PvE/BRD/BRD.cs
Fixes Override Logic for PP to use at 3 stacks, 2 if empy is about to be ready. Once in, bard opener is tested and functional.
> [BRD] OpenerRewrite Pitch Perfect edit

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- WrathCombo/Combos/PvP/BLMPVP.cs
Black Mage has been revisited for Patch 7.15.
- Complete logic rework.
- Fire and Blizzard spells have been condensed into one button.
- Smart Paradox usage for higher damage and fire-aspected uptime.
- Elemental Weave now accommodates both Fire and Ice wreaths.
- Several actions now have toggles to include defensive usage.
- Lethargy will no longer be used against NPCs.
- Xenoglossy prefers saving charges when used against NPCs.
- Aetherial Manipulation removed as it no longer grants Swiftcast.
- Removed all weaving checks and obsolete IDs.
- Added missing actionIDs for Fire/Blizzard III and High Fire/Blizzard II.
- Added `Aetherial Manipulation Feature` for quick debuff cleansing.
> [PvP] BLM Wrath Update

- WrathCombo/Window/Tabs/PvPFeatures.cs
> [UI] Fix PvP font scaling to match PvE

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/RDM/RDM_Config.cs
- WrathCombo/Combos/PvP/RDMPVP.cs
Red Mage has been revisited for Patch 7.15.
- Complete logic rework.
- Rearranged the flow, priority and conditions of all actions.
- Certain features will combo with one another when enabled.
- Enchanted Riposte combo and Scorch now behave as intended.
- Several actions now have toggles and/or sliders to improve usage.
- Resolution will no longer be used against NPCs.
- Most actions will no longer be used against players with immunity.
- Now prevents Jolt III from being spammed during player movement.
- Corps-a-corps can be used at any range within the defined maximum.
- Will no longer attempt to use Corps-a-corps or Displacement when bound.
- Removed all weaving checks and obsolete IDs.
- Added `Corps-a-corps / Displacement Feature` for quick debuff cleansing.
> [PvP] RDM Wrath Update

- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- WrathCombo/Combos/PvP/BLMPVP.cs
- WrathCombo/Combos/PvP/SAMPVP.cs
- WrathCombo/Combos/PvP/VPRPVP.cs
> [PvP] Misc. Fixes

- WrathCombo/Combos/PvE/WAR/WAR.cs
> [WAR] Fix Action for Inner Release

- WrathCombo/Combos/PvP/BLMPVP.cs
2 Bugs reported. 
1. When starting out, it forces you fire first even if you are trying to move. Ignoring the movement check waiting for astral fire. 
2. When moving, for some reason, when getting to umbral 3, instead of casting ice spells while moving, it was trying to cast fire spells and failing to operate. 
Removing this one tag, seems to have fixed both issues for me in testing.
> [BLM PVP] Movement Fix for requiring astral fire

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SMN/SMN.cs
This PR adds the following checks to the Emerald Ruin 3 replacement option:
- Add level check so it won't try to cast Ruin 3 when you haven't unlocked it yet (reported in Discord)
- Add movement check so it will use Emerald Ruin 3 if you are actively moving
> [SMN] Add movement and level checks to the Emerald Ruin 3 replacement option

- WrathCombo/Combos/PvE/BRD/BRD.cs
Changed the order of buffs in the bard code to match the balance.
Was
Lateweave radiant into BV/raging. 
Now
Lateweave BV int radiant/raging.
This will not improve numbers. But it will make it work better with the hard coded opener so my code doesn't have a gcd of drift on the 2 min fixing its buff order to get the extra gcd of 5% damage instead of increased direct hit chance. 
Added quick edit. 
Raging jaws was trying to happen without dots on a target bc the debuff check of being less that 35 was still coming back as a yes when it was not present. Weird interaction with chaotic switching targets. Simple moved it below the dot application so if something doesn't have dots it wont even consider raging strikes ironjaws refresh. It will apply dots.
> [BRD] Buff Realignment

- WrathCombo/Combos/PvP/NINPVP.cs
Shifted the Health check slider for seiton tenchu outside of the or statement so it also applies to unsealed Seiton techu
> [NIN PVP] Unsealed Seiton Tenchu Health Check

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRK/DRK.cs
- WrathCombo/Combos/PvE/DRK/DRK_Config.cs
- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/GNB/GNB_Config.cs
- WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
- WrathCombo/Combos/PvE/PLD/PLD.cs
- WrathCombo/Combos/PvE/PLD/PLD_Config.cs
- WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
- WrathCombo/Combos/PvE/WAR/WAR_Config.cs
- WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
> [Tanks] update One-Button Mitigations to have more HP% checks

- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DOL/DOL.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/DRK/DRK.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/NIN/NIN.cs
- WrathCombo/Combos/PvE/PCT/PCT.cs
- WrathCombo/Combos/PvE/PLD/PLD.cs
- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SMN/SMN.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
> Apologies for doing this after the codeowner addition, but it needed to be after a full merge.
The point of this endeavor was to ensure that all combos had action checks **before** logic started being applied, which is a drain on FPS.
While doing this, I also made all of the action checks consistent with each other in the following ways:
- Inverted any that had nesting
- Used "is" verbage for all of them, since that is what was dominant, and it is the same IL code in these cases
In doing this, <ins>**11**</ins> combos were fixed to no longer do any substantial logic before checking the action, <ins>**2**</ins> of which were particularly egregious
Just for reference, these combos were across:
- DNC
- MCH
- PCT
- RDM
- RPR
- SGE !
- SMN !
Most of these changes were very much a simple …
> [Core] Make combo action checks consistent

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/Combos/PvE/RDM/RDM_Config.cs
- WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
- WrathCombo/Combos/PvP/RDMPVP.cs
- WrathCombo/Window/Functions/Presets.cs
- Refactored TrySTMeleeCombo for AutoRot / Manual Riposte setup
- Kept Zwerchhau & Redoublement combo in TrySTMeleeCombo
- Rest of it (Riposte) to TrySTMeleeStart
- Riposte override + AutoRotation Detection
- Using Riposte to manually start the melee combo with Auto Rotation was broken
- Zwerchhau & Redoublement will now be placed on Jolts if Auto Rotation is active.
- Removed RDMPvP.Config Drawing from RDM_Config. Placed directly in RDMPvP
- Presets now has a PvP section for migrating PvP User Options Draw
> [RDM] AutoRot Edits, Start of PvP Config

- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/BRD/BRD_Config.cs
- WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
> [BRD] Openers and Adjustments

- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
I am submitting this pull request because an element is missing, probably due to a mistake.
If this opener is intended to start with a perfect balance, then this change is not necessary.
> [MNK] Dragon Kick added to Solar Lunar Opener

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
- Fixes Berserk/Inner release not changing
- Add Both to the tooltip
> [WAR] Fix Primal Combo -> Inner Release

- WrathCombo/Combos/CustomComboPreset.cs
The option is not actually being used in code and allowing such would cause issues
The buffs rely on radiant for timing in the 2 min window. Enabling buffs but not radiant throws off the burst window if people do not properly late weave radiant at the right time. It is just another buff and is already covered by the buffs section.
> [BRD] Remove Radiant Option from CCP

- docs/IPC.md
> [Docs] Update IPC docs for recent changes

- WrathCombo/Core/PluginConfiguration.cs
- WrathCombo/WrathCombo.cs
- Instead of immediately saving the plugin config it will now be added to a queue.\
Each framework update this queue gets worked, trying to save the queued configuration, and letting it retry a couple times.\
This fixes an issue where new-job-setups, where dozens of configs are being initialized and added to the plugin configuration at a time causes some file conflicts.
- This could likely be more efficient, such as batching saves, or only saving every X seconds, or something, but it is more efficient than it was before; this is the least-vast change to saving so as to minimize any sort of disruption.\
This does not require a change anywhere `Save()` is called.
> [Core] Process Config saves as a queue

- WrathCombo/Combos/PvE/BRD/BRD.cs
Ported the new buff setup from pr 270 to the simple and aoe modes for consistency and to fix #295 
Added buffcheck fix for barrage, it was having the issue, and radiant just to be safe.
> [BRD] update buffchecks + Buff fix for level 50

- WrathCombo/AutoRotation/AutoRotationConfigIPCWrapper.cs
- WrathCombo/Services/IPC/Enums.cs
- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/Leasing.cs
- WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
- WrathCombo/Services/IPC/Provider.cs
- WrathCombo/Window/Tabs/AutoRotationTab.cs
- WrathCombo/Window/Tabs/Debug.cs
- WrathCombo/WrathCombo.cs
- docs/IPC.md
> [IPC] Add `OnlyAttackInCombat`, various improvements

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/ALL/ALL.cs
- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/Combos/PvE/RDM/RDM_Config.cs
- WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
- WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- All
- Removed actionID passing to CanUseLucid (SGE/RDM/SCH/WHM calls updated)
- SGE
- Removed Ignore AoE Shield Check. Eukrasia Prognosis moved to priority system. Slider checks for total shields (Diagnosis/Prognosis) 
- RDM
- Cleanup, removed passing of actionID to all rotation functions execpt TryOGCDs. Reduced variables (out to ref) from rotation functions.
- Prioritized Preflugence in TryOGCDs
- Prevented Double CorpACorps or Engagments in the same oGCD window (Discord Report)
- Delayed Vice of Thorns until (hopefully) the next oGCD window (Discord Report)
> [RDM & SGE] Tweaks

- WrathCombo/Combos/PvE/DNC/DNC.cs
Oddly aoe only, no idea why. After technical finish it was locking on tech step as long as Tiliana was usable through the flourishing finish buff.
Buffcheck issue from techstep turning into Tiliana Added normal fix to the needtotech line. Fixes issue but doesnt explain why it wasn't happening to st, added there just to be safe though.
> [DNC] Buffcheck fix

- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
Fixes bug where it wont use hypercharge when wildfire is not on cooldown.
> [MCH] Hypercharge conditionals

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRK/DRK.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/PLD/PLD.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
- WrathCombo/Core/PluginConfiguration.cs
- WrathCombo/CustomCombo/Functions/Target.cs
- WrathCombo/Window/Tabs/Settings.cs
ST: added option to interject if the target's cast is interruptible
ST Simple: interrupts if the target's cast is interruptible
AoE: added options to interject if the target's cast is interruptible, or to stun if the target is casting
AoE Simple: interrupts if the target's cast is interruptible, and stuns if the target is casting
Which delays interrupts by X% of the total cast.
If a value is not passed to `CanInterruptEnemy()` then it will use this setting, and only return `true` if the cast is over that percentage done.
> [Tanks] Add interrupt into the combos, [Core] Rework settings tab

- WrathCombo/Window/ConfigWindow.cs
The image is present for all users, not just developers, as it's loaded into the Project in the `.csproj`; this can be double-checked by verifying the presence of the `images/wrathcombo.png` file in the [release zip](https://puni.sh/api/plugins/download/60/WrathCombo/versions/latest.zip).
This behavior was originally in c57078d, but immediately overwritten.
> [Core] Local Image

- WrathCombo/Services/IPC/Enums.cs
- WrathCombo/Services/IPC/HelpAutoRotConfig.cs
- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/Leasing.cs
- WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
- WrathCombo/Services/IPC/Provider.cs
- WrathCombo/Window/Tabs/AutoRotationTab.cs
- docs/IPC.md
- docs/IPCExample.cs
> [IPC] Fix UI, Add `Set` status codes

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRK/DRK.cs
- WrathCombo/Combos/PvE/DRK/DRK_Config.cs
- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
- WrathCombo/Services/IPC/Provider.cs
- WrathCombo/WrathCombo.cs
> [!TIP]
> See [this discord post](https://discord.com/channels/1001823907193552978/1336165865397424169) for a more visual list of what is being added in this PR, and for any feedback about this PR.
> Log Snippet comparisons:
> - [NEW Advanced mode](<https://xivanalysis.com/fflogs/a:FZtJHnx4PV2Tap68/1/2>)
> - [NEW Simple mode](<https://xivanalysis.com/fflogs/a:qjGXR4M96ntg2mYH/1/2>)
> - [Old Advanced mode](<https://xivanalysis.com/fflogs/a:FghR31pPbNayDLQ7/1/2>)
> [DRK] Simple Modes, In-Rotation Mit expansion, Rework

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvP/MCHPVP.cs
- WrathCombo/Combos/PvP/PVPCommon.cs
Added The buff from snake scales to the list of when to ignore the emergency features. Basically, Snake scales is active and none of those buttons can be pressed until you backlash to end it, or it ends on its own. The features were preventing you from backlashing to end it. 
Added Slither to the ignored movement action ids as well because I'm good like that. 
Jr pvp dev when?
Added target check to mch pvp burst as a quick fix Tauren mentioned. It encompasses all of the burst mode instead of the couple lines he already added so it wont use analysis without a target and potentially waste the buffed tool attack. 
Removed blazing shot option while I was at it, the game inherently changes the burst shot to blazing shot. You don't have a choice. Even with the option off, it does it because of …
> [VPRPVP] Emergency features / Snake Scales Fix. MCHPVP quickfix.

- WrathCombo/Combos/PvE/DNC/DNC_Config.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
> [DNC] Add `Peloton` back, add Tech openers

- WrathCombo/Combos/PvE/ALL/ALL.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/BLU/BLU.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvP/PVPCommon.cs
- WrathCombo/Combos/PvP/RDMPVP.cs
- WrathCombo/Core/IconReplacer.cs
- WrathCombo/CustomCombo/CustomCombo.cs
- WrathCombo/CustomCombo/WrathOpener.cs
to make it easier to spot and easier to track down all instances of this behavior
It's an action no longer in any job we use when we want to block input, it's not going to Action-Change, and we don't care if it does.
> [All] Use `All.SavageBlade` over `11`

- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/Commands.cs
- WrathCombo/Core/ActionReplacer.cs
- WrathCombo/Core/IconReplacer.cs
- WrathCombo/Core/PluginConfiguration.cs
- WrathCombo/CustomCombo/Functions/Action.cs
- WrathCombo/CustomCombo/WrathOpener.cs
- WrathCombo/Data/ActionWatching.cs
- WrathCombo/DebugFile.cs
- WrathCombo/Services/Service.cs
- WrathCombo/Window/Tabs/PvEFeatures.cs
- WrathCombo/Window/Tabs/Settings.cs
- WrathCombo/WrathCombo.cs
It is clamped to `0` - `1500`; values `0` and below all do the same thing, values over `1500` seem to break all weaves.
A value of `200` - `500` seems to be the most beneficial.
> [Core] Add Manual rotation throttle

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DNC/DNC_Config.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Add range checks to:
Adds new anti-drift recommendation feature:
> [DNC] Add range checks, anti-drift recommendation

- README.md
- WrathCombo/Commands.cs
- WrathCombo/Core/PluginConfiguration.cs
- WrathCombo/Window/Tabs/PvEFeatures.cs
- WrathCombo/Window/Tabs/Settings.cs
- WrathCombo/WrathCombo.cs
This simplifies the logic for each specific-Tab command, and prevents master commands from overwriting them.
(so you can always open the debug tab, not just on dev builds)
Without this, it was effectively just `OpenToCurrentJob`, but it didn't work immediately.
> [Core] Handle specific-Tab cmds better, add `pve` and `pvp`, add `combo` setting

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/ALL/ALL.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
- WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
- WrathCombo/CustomCombo/Functions/Status.cs
- WrathCombo/Extensions/UIntExtensions.cs
- WrathCombo/WrathCombo.cs
(Does not add this option, as it wouldn't work for a couple of reasons. Relies on `RetargetedActions`)
> [!NOTE]
> This includes #373.
> [Core] Apply Stance and Dance Partner

- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/Leasing.cs
- WrathCombo/Services/IPC/Provider.cs
- WrathCombo/Services/IPC/Search.cs
Now also won't cross wires between enabled/enabled in auto-mode for simple vs advanced.
This is the fix for the freeze some folks were getting.
> [IPC] Various Fixes, including Freeze

- WrathCombo/WrathCombo.cs
This fixes stance/partner not being upped on the first run with AD, but it happening on subsequent runs.
> [Core] Fix Stance+Partner upping

- WrathCombo/Combos/PvE/PCT/PCT.cs
- WrathCombo/Combos/PvE/PCT/PCT_Config.cs
Previously, there were situations where if we had to move outside our Ley Lines during `Starry Muse` windows it would force-use `Hammer Combo` over `Comet In Black` and `Holy In White` regardless of conditions, which would cause `Rainbow Bright` to not generate sometimes due to moving outside of buff or not being able to spend `Hyperphantasia` stacks quickly enough. 
This PR adds an option to both casts to prioritize using them immediately when inside Ley Lines over `Hammer Combo` while moving.
> [PCT] Add option to prioritize instant casts when `Inspiration` and `Hyperphantasia` are active

- WrathCombo/Commands.cs
- WrathCombo/Window/Tabs/PvEFeatures.cs
- WrathCombo/Window/Tabs/Settings.cs
- WrathCombo/WrathCombo.cs
> [UI] Minor fixes

- WrathCombo/Commands.cs
(Instead of simply saying it was "toggled")
Closes #388
`/wrath toggle 5001` gives `[WrathCombo] Simple Mode - Single Target set`
`/wrath toggle DRK_ST_Adv` gives `[WrathCombo] Advanced Mode - Single Target set`
> [Core] `/wrath toggle <x>` improvements

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
> [GNB] `Scuffed` options

- WrathCombo/Combos/PvE/DRK/DRK_Config.cs
- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
> [DRK] Improve Dark Arts usage

- WrathCombo/Combos/PvE/Content/Variant.cs
> [Core] Variant Inheritance logic fixes

- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/CustomCombo/Functions/Status.cs
- WrathCombo/Window/TargetHelper.cs
TargetHasRegen changed to handle a rare JobID being null
TargetImmuneToDamage's effect check fixed
SetTarget loops only once now to determine whom to give cards to
DrawTargetHelper better null handling
> [Core] Various Function Fixes

- WrathCombo/Combos/PvE/Content/Variant.cs
- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/CustomCombo/Functions/Cooldown.cs
@zbee If you don't mind, can you take a quick gander at DRK_Helper, and let me know if you want me to remove IsEnabled, or if you want to do something different.
> [Core] Removed legacy IsEnabled(uint). ActionReady handles it now.

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
- WrathCombo/WrathCombo.csproj
Patch Notes
Reworked Bard logic. Pooling now tied to buff cooldowns and not song status so it is possible to hold buffs without breaking the rotation. 
Added option, Apex Arrow pooling. It always pooled before how it is optional in case a fight has really bad timings.
> [BRD] Utilizing Helper file

- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/Provider.cs
Which helps prevent any errors from occurring when Wrath is used via IPC before the user has opened the Wrath UI
> [IPC] Add initial caching back

- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
Simple mode AoE fixed to use AoE defaults, not Single Target. Adv AoE fixed to use AoE values, not Single Target
> [RDM] AoE oGCD fixes

- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
This may not sound ideal on the surface, but consider that Oblation could prevent Living Dead
> [DRK] Minor Improvements

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/AST/AST.cs
Pooling option and small variant fix I saw was needed. 
#176 and discord request.
> [AST] Card pooling options

- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
The GetStatusEffect was not working and preventing any use of Regen. Rewrote it for GetStatusEffectRemainingTime, simplified yet functions as it should.
Added the missing !s to sage eukrasian diagnosis setup to make the shield checks function correctly again,. 
#501
> [WHM & SGE] Regen and shield fixes

- WrathCombo/Commands.cs
- WrathCombo/Core/PluginConfiguration.cs
- WrathCombo/Data/ContentCheck.cs
- WrathCombo/Window/Tabs/Settings.cs
(can still be overridden, like with `/wrath pvp` or `/wrath settings`)
Closes #492
> [Core] New setting: always open Wrath to the PvE Features tab

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
> [BRD] Radiant tweaks and missing option

- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/Leasing.cs
- WrathCombo/Services/IPC/Provider.cs
- WrathCombo/Services/IPC/Search.cs
- WrathCombo/Services/IPC/UIHelper.cs
- WrathCombo/Window/Tabs/PvEFeatures.cs
> [!IMPORTANT]
> Relies on ECommons bump to include NightmareXIV/ECommons#104 and NightmareXIV/ECommons@b89f56c
> [IPC] Fix cache for Job-Ready check, minor readability improvements

- WrathCombo/Commands.cs
- WrathCombo/DebugFile.cs
- WrathCombo/Window/Tabs/Settings.cs
> [Core] Add a couple Debug commands to help people with wine

- WrathCombo/CustomCombo/CustomCombo.cs
- WrathCombo/CustomCombo/Functions/Action.cs
- WrathCombo/CustomCombo/Functions/PlayerCharacter.cs
- WrathCombo/CustomCombo/Functions/Target.cs
- WrathCombo/Window/Tabs/Debug.cs
- Cached `OriginalHook(id)` value to reduce amount of function calls  `(4 → 1)`.
- Fixed `GetAttackType(id)` being passed instead of `GetAttackType(OriginalHook(id))`.
```
public static unsafe bool ActionReady(uint id)
{
uint hookedId = OriginalHook(id);
return ((GetCooldownRemainingTime(hookedId) <= RemainingGCD + 0.5f && ActionWatching.GetAttackType(hookedId) != ActionWatching.ActionAttackType.Ability) ||
HasCharges(hookedId)) && ActionManager.Instance()->GetActionStatus(ActionType.Action, hookedId, checkRecastActive: false, checkCastingActive: false) is 0 or 582 or 580;
}
```
- Replaced two `ContainsKey` lookups with one `TryGetValue` lookup.
- Refactored division into multiplication; added `(long)` cast to match time type.
```
public static bool JustUsed(uint actionID, float variance …
```
> [Core] Function Updates

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DNC/DNC_Config.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
> [DNC] Resolve more feature conflicts, Various improvements

- WrathCombo/Combos/PvP/ALL/ALL.cs
- WrathCombo/Window/Functions/UserConfig.cs
no possibility for out-of-range errors anymore.
> [PVP] Fix Out-of-Range Purify issues

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/GNB/GNB_Config.cs
- WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
- WrathCombo/Combos/PvE/WAR/WAR_Config.cs
- WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
- These are virtually identical to `GNB`'s options. Nothing special here.
- Both options include adjustable `Distance` & `Movement` thresholds, while `Onslaught` also contains an adjustable `Charges` threshold.
- The feature will now be housed on `Equilibrium` and no longer causes a conflict with `One-Button Mitigation Feature`
> [GNB/WAR] some big boy cleanup

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/BRD/BRD_Config.cs
> [BRD] Update to nowaste Handler

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
- Fixes `Air Anchor` from going off in AoE pre 76
- Auto check blazing shot/crossbow usage.
- Fix gauss/rico usage in AoE
> [MCH] fix AoE

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/PLD/PLD.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
> [Tanks] Add Single Target Stun

- WrathCombo/Data/ActionWatching.cs
- Fixes the error caused by using an action on an object not in the player's object list.
- Refactored `TimeSinceActionUsed` and `TimeSinceLastSuccessfulCast` with `TryGetValue`.
> [Data] ReceiveActionEffectDetour Null Fix

- WrathCombo/Combos/PvP/MCHPVP.cs
- Fixes the MCH `Eagle Eye Shot` code being tied to BRD's toggle.
> [MCHPvP] Eagle Eye Toggle Fix

- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/Provider.cs
- WrathCombo/WrathCombo.cs
> [IPC] Handle IPv6 better

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/PCT/PCT.cs
- WrathCombo/Combos/PvE/PCT/PCT_Config.cs
- WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
What it needs at this point. Is just lots of live testing and logs. So I can minimize the drift and make sure it is consistent. But I don't raid with it or main it. 
Updated Single Target Advanced to use the h2/h3 burst as well as clean some things up with adding some small pooling to make h2/3 work. As such, removed the choose your burst window spells options. Simply a choice on whether to use the optimized burst window. It won't function if you disabled half the spells.
Added Definitions to helperfile as well as burst window function and Hyperfantasia function.
Updated Aoe to match the single target setup retaining the holy in white option as it is a dps increase to not hold them
There is no optimized burst window option for aoe. 
Converted the advanced modes to simple modes. 
Cleaned …
> [PCT] 7.2 Pictoverhaul

- WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
Reported in discord. Someone didn't know to predraw motifs and led to weird issue. 
Opener wouldn't fire, burst window wouldn't draw the landscape to continue and got stuck in 123 limbo. 
Added an emergency landscape draw at beginning of burst window that wont interfere with normal operation, and an emergency blizzard in cyan at the end of burst window, to make sure you don't get locked out of 123 due to weird sub pallete stuff.
> [PCT] Fix for scuffed pulls

- docs/CODEOWNERS
@Taurenkey this does require @edewen be on [the team](https://github.com/orgs/PunishXIV/teams/teamwrath)
> [Meta] Add new Team Member ownership, adjust VPR ownership

- WrathCombo/Combos/PvE/PLD/PLD.cs
Issue was somewhat obscure, but should now be resolved for good.
Culprit(s):
- `ActionReady` has an embedded `OriginalHook`, checking whatever the action changed into.
- The game's native action change function affects this.
- Directly calling an action that has changed into something else will hang the logic.
```
// Blocked by Goring Blade
// Fight or Flight is not ready, but Goring Blade is
if (ActionReady(FightOrFlight))
return FightOrFlight;
```
```
// Resolved
// We ensure Fight or Flight hasn't changed into anything else first
if (OriginalHook(FightOrFlight) is FightOrFlight && ActionReady(FightOrFlight))
return OriginalHook(FightOrFlight);
```
> [PLD] Fix Fight or Flight Blocking AoE Modes

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
Expanded on already existing self cleanse setup with Warden's Paeon to use the retargeting system to detect and cleanse party as well. Optional in Advanced. 
Tested in Sohm Al. Cleansed Ysayle of her unwanted DD
> [BRD] Retargetted Warden's Paeon

- WrathCombo/Combos/PvE/AST/AST_Helper.cs
> [AST] Improve Card target-picking reliability

- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
> [DNC] Don't change Partners just because of range

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
> [WAR] Add `Holmgang` Retargeting

- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
When popping Presence of mind, The Actionready picks up the original hook ready from glare 4, and when weaving, it shows a greyed out Pom. 
This fixes that weird looking attempt at weave during the Pom Burst window. 
Added New status cap code to needsdot()
> [WHM] Status Effect Cap Code +Pom Visual fix

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
Initial work on making polyglot usage a bit more flexible.
- Added a slider that allows user to select how many chargers to keep for manual use, seperate from the movement option slider
- Removed the "USE ASAP" option as slider can be set to "0" to recreate the same behavior
- Make the movement slider and manual usage slider not conflict with each other.
- Added priority movement options
> [BLM] Polyglot usage tweaks

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/CustomCombo/Functions/Party.cs
- WrathCombo/CustomCombo/SimpleTarget.cs
- WrathCombo/Data/ActionWatching.cs
- WrathCombo/WrathCombo.cs
> [Retargeting] Fix DNC+AST+WHM

- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/Combos/PvE/ALL/HealRetargeting.cs
- WrathCombo/CustomCombo/CustomCombo.cs
- WrathCombo/Data/StatusCache.cs
- WrathCombo/Extensions/GameObjectExtensions.cs
> [Core] Fix `StatusList` crashes

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SMN/SMN.cs
- WrathCombo/Combos/PvE/SMN/SMN_Config.cs
- WrathCombo/Combos/PvE/SMN/SMN_Helper.cs
More adjustments for Summoner in line with Dawntrail Changes.
1. Removed the Burst Delay Option. This was needed when the 2 minute buff was 30 seconds long and popped on pull before the Demi. Now that it is 20 seconds and popped during demi. Setting it to 3 GCDS can very easily push OGCDS out of the demi summon window when pooling. Resulting in a need for the Emergency Demi Dump. Leaving that there for now.
2. Removed the any searing burst option checkbox. The code still looks for any searing, Just removed it as a choice. No other classes are concerned with 2 of the same class in a raid and set up several lines of code around it.Because it accounts for any burst. If another summoner IS with you, and you have demi only burst selected it will on its own start running with the next demi …
> [SMN] Cleanup 2.0

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/ALL/ALL.cs
- WrathCombo/Combos/PvE/ALL/ALL_Config.cs
- WrathCombo/CustomCombo/SimpleTarget.cs
- WrathCombo/Window/Functions/Presets.cs
- WrathCombo/Window/Tabs/Settings.cs
> [Tanks] Add Shirk Retargeting Feature, threshold for Double Reprisal Protection

- WrathCombo/Window/Tabs/Debug.cs
- `System` actions have a `UnlockLink.RowId` value of `1` but no quest associated with them, resulting in an error.
> [UI] Fix Sheet Display Error for System Actions

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRK/DRK.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/PLD/PLD.cs
- WrathCombo/Combos/PvE/PLD/PLD_Config.cs
- WrathCombo/Combos/PvE/PLD/PLD_Helper.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
- WrathCombo/Combos/PvE/WAR/WAR_Config.cs
- WrathCombo/Core/ActionRetargeting.cs
> [TANK] Retargetting Things

- WrathCombo/WrathCombo.csproj
> Preferably NightmareXIV/ECommons#118 is merged in time to be included in this, as that's most of the fix for building on Linux, but it's not required if you're not on Linux.
> [Core] Add build output directories specific to each OS

- WrathCombo/Combos/PvE/WAR/WAR.cs
- WrathCombo/Combos/PvE/WAR/WAR_Config.cs
- WrathCombo/Combos/PvE/WAR/WAR_Helper.cs
- WrathCombo/Window/Functions/UserConfig.cs
Since the values we're working with typically don't require precision beyond the first decimal place, supporting flexibility from one to three should be okay here and for other use-cases with other jobs. 
The default param set (3) will keep behavior as is for the other references, and now devs can set `decimals: 1` to reflect this behavior here in the screenshots with the slider moving in increments of `0.1` instead of `0.001`. 
I will admit this feels kind of lazy, or is this just really that simple? idk, but this works fine from testing😄
Let me know if there's a better way you'd like this done.
> [WAR/Core] `Stationary Only` Delay Check + small `DrawSliderFloat` param for decimal places

- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
> [AutoRot][DNC][AST] Fix null error upon entering combat

- WrathCombo/Combos/PvP/SMNPvP.cs
Shifted a couple things around to allow for a more frontloaded burst. And less chance to waste an r4 proc. 
Start with 2 Ogcds which sucks but then it will knock out 30k in 2 gcds followed by another 32k in 3 gcds. 
Added a line to throw up savage blade if target is immune during an r4 proc. It replaces ruin 3, so it is the only way to prevent a wasted proc.
> [SMN PVP] Tweaks for burst, and prevent r4 waste

- WrathCombo/CustomCombo/SimpleTarget.cs
> [Core] Add null checking to the last `SimpleTarget`s

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- docs/CODEOWNERS
- General
- Cleanup and regions for all sch stuff
- Removed redundant options
- Reorganized CCP to be more logical
- ST
- Rewrote Dots in whm style
- Split Chain Stratagem and Baneful Impaction into 2 options
- AoE
- Added Chain Stratagem with a optional Level Check for Baneful Impaction
- Added Baneful Impaction
- Added Energy Drain
- ST Heals
- Added Adloquim to the ST priority System
- Added Emergency Tactics as a option on Adloquim with a separate health slider
- Added Fey Blessing, Illumination, and Whispering dawn to ST with Non Boss Option for dungeon trash (single target options   were lacking there and was using gcds to heal too often with autorotation)
- Added the Dissolve union to all 4 combos. Will not affect dps, but it is needed for auto rotation to turn off Aetherpact when …
> [SCH] WellReadMage Overhaul

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/Combos/PvE/Content/OccultCrescent/OccultCrescent.cs
- WrathCombo/Combos/PvE/Content/OccultCrescent/OccultCrescent_Helper.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/CustomCombo/Functions/Misc.cs
- WrathCombo/Data/ActionWatching.cs
- WrathCombo/Window/Tabs/AutoRotationTab.cs
- WrathCombo/WrathCombo.csproj
- Merged Zbees IPC changes into this so I could do this stuff without conflicts of ccp. 
- SCH
- Added Simple Dps Mode for ST and AoE
- Cleaned up UI. Utilized configs to remove some ugly parent boxes. 
- Changed Button selection to radio buttons for a cleaner look and smoother function
- Adjusted how boss and slider options work for chain strategem to be in line with more recent works.
- I froze my dic
- AST
- Added Simple DPS mode for ST and AoE
- Adopted Dot Checker Function from SCH that Stole it from WHM for cleaner dot section
- I froze Taurens dic
> [Healers] Cleanup, Simple Modes. Merge #682 first

- WrathCombo/Combos/PvE/BLU/BLU.cs
Added a `!JustUsed(MoonFlute)` to all instances of MoonFlute on lvl 70 and 80 combos to avoid double casting it due to latency. @zbee
> [BLU] MoonFlute Fix

- WrathCombo/Combos/PvE/WHM/WHM_Config.cs
- WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
- Added the **Only Bosses** option to DoT uptime for WHM
- Refactored a bit how the HP Treshold is calculated
- Renamed BossAvoidance to DotEnemyRestriction in WHM module
<details>
<summary>Proposed design</summary>
| Checkbox at start | Avoid adds option | Double slider |
| -- | -- | -- | 
| More flexibility on allowed targets, still the same HP% for all selected | Not much UI Changes, easy to understand, still the same HP% for all selected | Change the UI, more configurations | 
| <img width="742" height="263" alt="image" src="https://github.com/user-attachments/assets/c413c4c9-43f6-4fcd-ac2c-9674fc8a7f7b" /> | <img width="777" height="260" alt="image" src="https://github.com/user-attachments/assets/e15bfb87-559d-410a-8bc5-ed562fa18cf0" /> |  <img width="866" height="253" alt="image" …
> [WHM] Add Only Bosses option to DOT

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
- WrathCombo/Combos/PvE/GNB/GNB_Config.cs
- WrathCombo/Combos/PvE/PCT/PCT.cs
- WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- WrathCombo/Combos/PvE/SMN/SMN_Helper.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/CustomCombo/Functions/Action.cs
- WrathCombo/Window/Functions/Presets.cs
`CanSpellWeave()` was obsoleted in #689, with a direct replacement for the logic in `CanWeave()`
Weave count is now managed by a global setting (defaulted to `2`) handled within `CanWeave`.
@edewen AST used `CanSpellWeave()` about a billion times, may want to group together the oGCDs under a big `if (CanWeave())` like many other jobs do, if possible.
> [Core] Squash Obsolete Warnings

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
- WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
- WrathCombo/Combos/PvE/SMN/SMN.cs
- WrathCombo/Combos/PvE/SMN/SMN_Config.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
DRG
- Make `CanDRGWeave` an expression
MCH
- better phrasing of queen usage in MCH ST (no functional changes)
BLM
- Optimize `B1/B3` standalone option
- Optimize `F1/F3` standalone option
- Add combat check to `Fire 4 to 3`
- Add new standalone option `Freeze to Paradox`
- Add new standalone option `Flarestar to Paradox`
- Add new standalone option `Freeze to Blizzard II`
- Fix `ActionReady` and `Levelchecked` usage
- Added Levelchecks for pre 35 Transpose usage
- Fixes #698 
VPR
- Add better Reawaken usage for Simple mode ( dont use below 5%)
SMN
- Add Crimson Cyclone range slider
> [Various] some weekly stuffs

- WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
It was overwriting grand impact. Fixed the logic to match non movement and swiftcast stuff to check CanInstantCD instead of the half list. Dont know why i never did that to begin with.
> [RDM] Acceleration movement fix.

- WrathCombo/Core/PluginConfiguration.cs
- WrathCombo/Window/ConfigWindow.cs
It is now the width of the plugin icon, plus some, instead of 1/3 the window size.
(which is the plugin icon's width)
If the user reduces the size below the minimum, the column sets itself to be non-resizable (to stop the drag event), and sets itself to the default column width.
To prevent the loss of being able to crunch the sidebar down to its minimum size (which was never zero) I have also added a collapse button.
When pressed, it redraws the window to a table with a singular column for only the body of the content, removing the sidebar.
(note: this also changes the ID of the table, to prevent the sidebar being set to the full width of the window when un-collapsed after being collapsed)
> The code diff is not particularly readable on GitHub nor SemanticDiff, because the code needed …
> [UI] Update Sidebar's default size, +min size, +collapse button

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/AST/AST_Config.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
Added option for early stellar detonation, with boss toggle and hp slider to help prevent waste on dungeon trash. Properly set for non bosses would not interfere with the party hp check for aoe healing that also exists. At least how I would use it. 
did a quick fix for dancer issue not using fans at lower levels. it was being blocked in st from it trying to pick a dance partner before it was high enough to use closed position
> [AST] Early Stellar Detonation Option + dancer tiny fix for level check

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/ALL/Roles/RoleActions.cs
- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/AST/AST_Config.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/Combos/PvE/Content/Variant/VariantActions.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
- WrathCombo/Combos/PvE/DRK/DRK.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/Combos/PvE/WHM/WHM_Config.cs
- WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
- WrathCombo/Core/ActionRetargeting.cs
- WrathCombo/CustomCombo/Functions/Target.cs
- WrathCombo/CustomCombo/SimpleTarget.cs
- WrathCombo/Data/StatusCache.cs
- WrathCombo/Extensions/GameObjectExtensions.cs
- WHM Update
- Simple DPS Modes Added for ST and AOE
- Updated how ST advanced selects its button replacement  
- Added Priority List spell selection to ST and AOE Healing
- ! Raidwide Detection Features, is utilized in all 4 advance combos  
- ! ST Movement Options
- ! AoE Multi-dotting Option
- Set target threshold, Health Threshold, and Refresh time
- ! ST and AoE Mitigation Features on Asylum and Aquaveil for manual healers
- Retargeting Standalone Features added
- Cure 1 and 2
- Afflatus Solace
- Aquaveil
- Asylum
- Liturgy of the Bell
- Cure 3
- Benediction
- Regen
- Tetragrammaton
- Divine Benison
- SCH and AST Update
- ! Raidwide Detection Features, is utilized in all 4 advance combos
- ! AoE Multi-dotting Option
- Set target threshold, Health Threshold, and Refresh time
> [WHM] Priority Treatment

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/BRD/BRD_Config.cs
- WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
- WrathCombo/Combos/PvE/PCT/PCT.cs
- WrathCombo/Combos/PvE/PCT/PCT_Config.cs
- WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/Combos/PvE/RDM/RDM_Config.cs
- WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
- WrathCombo/Combos/PvE/SMN/SMN.cs
- WrathCombo/Combos/PvE/SMN/SMN_Config.cs
- WrathCombo/Combos/PvE/SMN/SMN_Helper.cs
- !Upgraded Feature RDM OGCD Standalone Customization
- !Upgraded Feature RDM Riposte Melee Combo added OGCD weave options
- !Upgraded Feature RDM Moulinet Melee Combo added OGCD weave options
- !Adjusted Feature PCT Burst Mode adjusted to 7.3 Hammer changes to use standard burst per balance
- Cleaning (SMN, PCT, BRD, RDM)
- Used Alias to turn CustomComboPreset into Preset 
- Cleaned a buttload of emptylines for no reason
- using static config. so I dont need to type Config.
> [Various] Edewen DPS Classes Small Cleanups and Additions

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Config.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/RPR/RPR_Config.cs
- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
BLM
- Update Standalone options
- Update Fire I / Fire III
- Update Blizzard 4 to Despair
- Add option to choose B4 or B3
- Fix Fire 1 to Despair
- Add needing a battle target for movement options
- Closes #726 
MNK
- Add in opener prepull.
- Add Thunderclap retargetting
- Condense `ROF- BH` and `BH - ROF` into 1 option where u can choose the button.
- Update Perfect Balance usage 
- Made sure Fire's reply is always inside buff windows
- update Wind's reply usage to be used in buffs when possible
RPR
- Update to follow new graph
Various
- cleanups of unneeded Parenthese
- Transformed most to switch or switch expressions
> [Various] General code cleanup/BLM - MNK - RPR Updates

- WrathCombo/AutoRotation/AutoRotationConfigIPCWrapper.cs
- WrathCombo/Services/IPC/Enums.cs
- WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
- WrathCombo/Services/IPC/UIHelper.cs
- WrathCombo/Window/Tabs/AutoRotationTab.cs
> [IPC] Expose `DPSSettings.DPSAoETargets`

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
- Add in `ActionID is not` to standalone combo's where it was forgotten or removed
Will probably need a second pair of eyes to make sure they all behave as before.
It is late, i will also doublecheck tomorrow when im fully awake
> [Various] Kage's Class Cleanup

- WrathCombo/Data/Conflicts/ConflictingPlugins.cs
- WrathCombo/Data/Conflicts/ConflictingPluginsChecks.cs
- WrathCombo/Services/IPC_Subscriber/BossMod.cs
Currently if BossModReborn is installed Wrath will throw warnings every 10 or so seconds, which is annoying.\
This is due to it not working with BMR's IPC Name or AI Config. This PR fixes both, expected to release next Sunday or so.
> [Core] Fix BossModReborn Conflicts

- WrathCombo/AutoRotation/AutoRotationController.cs
> [Core] Undo Auto-Rotation Targeting change

- WrathCombo/CustomCombo/Functions/Status.cs
- WrathCombo/CustomCombo/SimpleTarget.cs
- WrathCombo/Extensions/GameObjectExtensions.cs
> [Core] Make Multi-Dot not Pull enemies

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/RDM/RDM.cs
- WrathCombo/Combos/PvE/RDM/RDM_Config.cs
Added options to the Aero and Thunder standalones to customize what buttons it replaces with.  Mirrored it adding an aoe version
> [RDM] Aero and Thunder Standalone Update

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/NIN/NIN.cs
- WrathCombo/Combos/PvE/NIN/NIN_Config.cs
- WrathCombo/Combos/PvE/NIN/NIN_Helper.cs
- Doton time stood still timer
- Feint check for any owner
- Canapplystatus check for feint, trick, and mug
- Fix for missing level check. Aoe 1-2 combo
- Added line to hide feature so it shows trick attack if mug is not selected and in combat. Not just only when you have suiton. 
- !New Feature Simpler Mudras Alternate Feature
- Ten = ST Mudras, Chi = Aoe Mudras without Doton, Jin = Doton
> [NIN] Little fixes

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvP/ALL/ALL.cs
- WrathCombo/Combos/PvP/ASTPVP.cs
- WrathCombo/Combos/PvP/BLMPVP.cs
- WrathCombo/Combos/PvP/BRDPVP.cs
- WrathCombo/Combos/PvP/DNCPVP.cs
- WrathCombo/Combos/PvP/DRGPVP.cs
- WrathCombo/Combos/PvP/DRKPVP.cs
- WrathCombo/Combos/PvP/GNBPVP.cs
- WrathCombo/Combos/PvP/MCHPVP.cs
- WrathCombo/Combos/PvP/MNKPVP.cs
- WrathCombo/Combos/PvP/NINPVP.cs
- WrathCombo/Combos/PvP/PCTPVP.cs
- WrathCombo/Combos/PvP/PLDPVP.cs
- WrathCombo/Combos/PvP/RDMPVP.cs
- WrathCombo/Combos/PvP/RPRPVP.cs
- WrathCombo/Combos/PvP/SAMPVP.cs
- WrathCombo/Combos/PvP/SCHPVP.cs
- WrathCombo/Combos/PvP/SGEPVP.cs
- WrathCombo/Combos/PvP/SMNPvP.cs
- WrathCombo/Combos/PvP/VPRPVP.cs
- WrathCombo/Combos/PvP/WARPVP.cs
- WrathCombo/Combos/PvP/WHMPVP.cs
- WrathCombo/CustomCombo/SimpleTarget.cs
- WrathCombo/Extensions/GameObjectExtensions.cs
All General Cleanup. Inverting IFs, Removing Deadspace;
Every job has seen at least one CC on full one button to ensure casual player readiness after all the inverting.
> [PVP] 7.3 Update

- WrathCombo/Combos/PvP/VPRPVP.cs
- added First through Fourth generation to action ID check. So that in performance mod it doesnt ignore the combo during lb and the ogcd legacy attacks go off.
> [VPRPVP] LImit break fix for performance mode

- WrathCombo/CustomCombo/Functions/Target.cs
- WrathCombo/Data/ActionWatching.cs
- WrathCombo/Extensions/GameObjectExtensions.cs
This makes a couple of fixes, focused around not including the hitbox in the distance check for ground-targeted action placement and checking that the target is over the ground.
Most predominant are the changes on a boss like Cloud Deck where they are not over the ground (should now place on the ground nearest the boss), wall bosses like P7S where they are not technically over the ground (should now place on the ground nearest the boss), and targets that were too far away to actually place correctly (should now place on the ground nearest the boss, that is actually within range).
> [Retargeting] Better Ground-Targeted Placement

- WrathCombo/Window/Tabs/AutoRotationTab.cs
The checkbox to enable Orbwalker integration was permanently disabled due to the wrong IPC being used. It will now check the OrbwalkerIPC instead. I also added some help text about the Buffer Initial Cast setting in the Orbwalker plugin for those who may have issues with casting while moving. Built and tested locally
> [UI] Fixed Orbwalker Integration Button in Autosettings + Misc
