PunishXIV/WrathCombo

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/BLM/BLM.cs
- XIVSlothCombo/Combos/PvE/BLM/BLM_Helper.cs
- XIVSlothCombo/Combos/PvE/DRG/DRG.cs
- XIVSlothCombo/Combos/PvE/DRG/DRG_Helper.cs
- XIVSlothCombo/Combos/PvE/MCH/MCH.cs
- XIVSlothCombo/Combos/PvE/MCH/MCH_Helper.cs
- XIVSlothCombo/Combos/PvE/MNK/MNK.cs
- XIVSlothCombo/Combos/PvE/MNK/MNK_Config.cs
- XIVSlothCombo/Combos/PvE/MNK/MNK_Helper.cs
- XIVSlothCombo/Combos/PvE/RPR/RPR.cs
- XIVSlothCombo/Combos/PvE/RPR/RPR_Helper.cs
- XIVSlothCombo/Combos/PvE/SAM/SAM.cs
- XIVSlothCombo/Combos/PvE/SAM/SAM_Helper.cs
- XIVSlothCombo/Combos/PvE/VPR/VPR.cs
- XIVSlothCombo/Combos/PvE/VPR/VPR_Helper.cs
- XIVSlothCombo/Window/Functions/Presets.cs
> various class fixes

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/PCT/PCT.cs
> [PCT] add swiftcast motifs option

- XIVSlothCombo/Combos/PvE/RPR/RPR.cs
Rewrite Dyn TN to not cut FPS in half
> [RPR] Fix lagspikes

- XIVSlothCombo/Combos/PvE/DRG/DRG.cs
- XIVSlothCombo/Combos/PvE/MCH/MCH.cs
- XIVSlothCombo/Combos/PvE/RPR/RPR.cs
- XIVSlothCombo/Combos/PvE/SAM/SAM.cs
- XIVSlothCombo/Combos/PvE/VPR/VPR.cs
- Add missing ActionID's
- merge #56 in here 
- closes #79
> [Various] Add missing ActionID at end of combo

- XIVSlothCombo/Combos/PvE/RPR/RPR.cs
> [RPR] Remove SoD Check

- XIVSlothCombo/Combos/CustomComboPreset.cs
- XIVSlothCombo/Combos/PvE/ALL/ALL.cs
- XIVSlothCombo/Combos/PvE/GNB/GNB.cs
- XIVSlothCombo/Combos/PvE/GNB/GNB_Config.cs
- XIVSlothCombo/Combos/PvE/GNB/GNB_Helper.cs
- XIVSlothCombo/Combos/PvE/WAR/WAR.cs
- XIVSlothCombo/XIVSlothCombo.csproj
Resubmit of #61, PR was broken (thanks bot)
fixes #68
> [GNB] 7.1 minor rotation refactor, mitigation support .. plus some WAR stuff

- XIVSlothCombo/Combos/PvE/PCT/PCT.cs
- XIVSlothCombo/Combos/PvE/PCT/PCT_Config.cs
Added starstruck to landscape motif option just like hammer and mog. Requested in disc
> [PCT] Combined Motifs Update

- XIVSlothCombo/Combos/PvE/WAR/WAR.cs
> [WAR] PrimalRendReady fix

- XIVSlothCombo/Combos/PvE/MCH/MCH.cs
> [MCH] Fix autorot weaving

- XIVSlothCombo/Combos/PvE/GNB/GNB.cs
- XIVSlothCombo/Combos/PvE/GNB/GNB_Config.cs
- XIVSlothCombo/Combos/PvE/GNB/GNB_Helper.cs
> [GNB] AoE & Mitigations fixes/adjustments

- README.md
- Should be able to provide a one-click link for this
> [Meta] Update Readme

- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Core/PluginAddressResolver.cs
- WrathCombo/Data/ActionWatching.cs
<sub>Plus an update to a remaining mention of Sloth</sub>
> [CORE] +`HasWeaved()`

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/ALL/ALL.cs
- WrathCombo/Combos/PvP/PVPCommon.cs
- WrathCombo/CustomCombo/Functions/Party.cs
> [Core] Misc. Fixes

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
- add Legacys on Generations
Was askled in Discord
> [VPR] new option

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- Add 1 button ogcd for gluttony on bloodstalk option
- closes #88
> [RPR] add gluttony on bloodstalk option

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- Add Choatic spring combo
- Add Heaven's Thrust combo
> [DRG] New option

- WrathCombo/Combos/PvE/AST/AST_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
- WrathCombo/Combos/PvE/WHM/WHM_Config.cs
Added defaults for some heal options and 100% on Esuna. Options should "work" now that they're at some value and users can tweak percentages down from there
> [Heals] Default Sliders for New Users

- WrathCombo/Combos/PvP/PVPCommon.cs
- WrathCombo/Window/Functions/UserConfig.cs
Added WHM cc, Miracle of nature, to the options for purify using the checkboxes. With great struggle and a lot of help from zbee.
> [PVP] Purify WHM CC

- WrathCombo/Combos/PvP/NINPVP.cs
Added SeitonUnsealed Buff to the code for Seiton Tenchu so it can do the followup LB attack.
> [PVP] Nin Seiton Unsealed fix

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
> [VPR] Serpents Tail standalone option

- WrathCombo/Combos/PvE/DRK/DRK.cs
- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
- WrathCombo/Combos/PvE/PLD/PLD.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- WrathCombo/CustomCombo/Functions/Target.cs
> [SAM] higanbana

- WrathCombo/Combos/CustomComboPreset.cs
> [SCH] Fix Esuna option not showing

- WrathCombo/Combos/PvE/SMN/SMN.cs
Moved the last bit of the swiftcast egi part into the correct code block.
> [SMN] Fixed swiftcast egi feature.

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
Fixed Discord issue "PCT Simple Mode Single Target Issue" where it woudn't know what opener to use so i've added a default one when Simple ST mode is enabled.
> Fix PCT SimpleMode + Add Preset confilicts

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Config.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
> [VPR] Various

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
> [MCH] Various Fixes

- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/Combos/PvP/PVPCommon.cs
- WrathCombo/CustomCombo/CustomCombo.cs
- WrathCombo/CustomCombo/Functions/Action.cs
- WrathCombo/Data/ContentCheck.cs
Squashes the following compiler warnings across several files:
> [Core] Squash warnings

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
- Update BLM Flare mana usage to correct value
- Add Air Anchor to AoE
- Update Simple AoE Reassemble usage
- Cleanup
> [BLM] + [MCH] Updates

- WrathCombo/Combos/PvE/PLD/PLD.cs
> [PLD] Possible Low FPS Fix

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Config.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/RPR/RPR_Config.cs
- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Config.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
- update all my classes (BLM, DRG, MCH, MNK, RPR, SAM, VPR) to be uniform
- remove helper in helper
- reorder customcombo
> [Various] Update classes

- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- Fix AA in Advanced AoE
- Fix CanSpellWeave error in BLM
> [MCH] fix AA in advanced AoE

- README.md
> [Meta] Add `ignore command` to the readme

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
> [DNC] Update descriptions

- WrathCombo/WrathCombo.cs
> [Core] Fix `set` and `toggle` commands

- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/UIHelper.cs
> [IPC] Callback fixes

- CONTRIBUTING.md
- docs/IPC.md
- docs/IPCExample.cs
> [Docs] add IPC guide

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DNC/DNC_Config.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
Thank you @edewen 
Thank you, again, @edewen
(to disable the DP feature during Auto-Rotation settings, until targeting is available)
> [DNC] Add Simple Modes

- docs/CODEOWNERS
> [!WARNING]
> This should be merged LAST before an update, to avoid spam pinging OWNERS of existing PRs.
- Should just serve to auto-request review from CODEOWNERS, without any Repository Settings changes.
- The Branch Protection Rules could be modified to REQUIRE a review from the OWNER of a file, however I don't see much benefit from this currently.
- If this setting change is to be made, the CODEOWNERS file needs adjusted somewhat.
> (MERGE LAST) [Docs] Add CODEOWNERS

- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- WrathCombo/CustomCombo/WrathOpener.cs
- Add Prepull
- Add meikyo updates
> [SAM] Opener

- WrathCombo/Combos/PvE/BRD/BRD.cs
Same fix as last pr but to simple too. putting dot reapplication above raging jaws logic. simple shift of text.
> [BRD] Fix the raging jaws for simple too

- WrathCombo/CustomCombo/Functions/Action.cs
Added some guardrails incase out of habit Weave(ActionID) happens
> Weaving guardrails (Obsolete use check)

- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- Added Dissolve Union HP% slider to Single Target Heals - Aetherpact
> [SCH] Aetherpact's Dissolve Union 

- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
-Added a slider to hold onto 0 or 1 Phlegma Charges
-Closes #65
> [SGE] Phlegma Hold

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/ALL/ALL.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DNC/DNC_Config.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
- WrathCombo/Core/PluginConfiguration.cs
> [DNC] Reverse order of new features, support Custom Steps in other Features

- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
> [SAM] Optimize everything

- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
- Make reawaken code easier to adapt
- Move ID's to helper
> [VPR] Some cleanup

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
- WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
- WrathCombo/CustomCombo/WrathOpener.cs
- Add Pneuma to AoE DPS
- Add Pneuma to AoE Healing ( WiP)
- Add Boss Checks Chain Stratagem
- Cleanup
> [SGE] & [SCH] Various

- WrathCombo/WrathCombo.csproj
I was trying to make changes on a fork on my Macbook and noticed I couldn't build the project. I copied the logic from PunishLib https://github.com/PunishXIV/PunishLib/blob/fd8fd4418f6a3a8cd97a8c2179a54f1abdd9513b/PunishLib/PunishLib.csproj
> added DalamudLibPath handling for MacOS and Linux

- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Config.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
> [VPR] update buffchecks + cleanup

- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
> [SAM] update buffchecks + cleanup

- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/RPR/RPR_Config.cs
- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
> [RPR] update buffchecks + cleanup

- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Config.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
> [MNK] update buffchecks + cleanup

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
> [MCH] update buffchecks + cleanup

- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/DRG/DRG_Config.cs
- WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
- update buffchecks + cleanup
Fixes #306
> [DRG] update buffchecks + cleanup

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
`Storm's Path` -> `Heavy Swing`
also minor fix to issue with `Storm's Path` option icon
> [WAR] actionID swap

- WrathCombo/Window/Tabs/Debug.cs
- docs/IPC.md
> [IPC] Update Debug Section

- WrathCombo/Window/Tabs/Debug.cs
- WrathCombo/WrathCombo.cs
> [Core] Reorganize and Collapse Debug

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
> [SAM] dynamic meikyo usage

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- Add Brotherhood - Riddle of Fire option
- closes #330
> [MNK] add BH - RoF option

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- Add Soulsow option to Simple ST/AoE and Advanced ST/AoE
> [RPR] Add soulsow to rotation

- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
> [SGE][SCH] Optimize AoE Heals code

- WrathCombo/Combos/CustomComboPreset.cs
> [UI] Remove references to old UI

- WrathCombo/Combos/PvE/RPR/RPR.cs
> [RPR] Soulsow

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/DRG/DRG_Config.cs
- WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
> [DRG] Opener + updates

- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
- Add pooling for Gauss and Ricochet
- Closes #339
> [MCH] Add gauss rico pooling

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRK/DRK_Config.cs
- WrathCombo/Combos/PvE/DRK/DRK_Helper.cs
- WrathCombo/Window/Tabs/PvEFeatures.cs
> [DRK] Fix ST `Salted Earth`, add AoE Mana limit

- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/AST/AST_Config.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/Combos/PvE/DRG/DRG_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
- WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/Combos/PvE/WHM/WHM_Config.cs
- WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
- WrathCombo/Services/IPC Subscriber/IPCSubscriber.cs
- Add Bosscheck to DoT uptime
- remove hp% slider for DoT
- ran cleanup
> [Healers] Dot update

- WrathCombo/Combos/PvE/DRG/DRG.cs
- Add Wyrmwind logic for burst
> [DRG] Wyrmwind logic

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG_Config.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Config.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/RPR/RPR_Config.cs
- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Config.cs
> [Various] Bosschecks

- README.md
> [Meta] Add Orbwalker to the Readme

- WrathCombo/Services/IPC/Leasing.cs
- WrathCombo/Window/Tabs/Debug.cs
> [!IMPORTANT]
> This depends on NightmareXIV/ECommons#94.
> @Taurenkey I actually requested some feedback from you on that PR.
> [Core] Improve debug tab further

- WrathCombo/WrathCombo.csproj
> [Core] Enable building on *nix systems

- WrathCombo/Combos/PvE/SGE/SGE.cs
Taurochole will become Druochole when player level is below Taurochole
Fixes #378
> [SGE] Taurochole adjustment

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
- makes opener respect positional choice
- remove broken SAM opener substitute
> [RPR] + [VPR] Add positional opener

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/RDM/RDM_Config.cs
- WrathCombo/Combos/PvE/RDM/RDM_Helper.cs
> [RDM] Some `Acceleration` stuff

- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
> [MCH] Rework hypercharge logic

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
> [MNK] Optimization

- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
- Fix Gluttony not being used with new Bosschecks
- Fix Shadow of Death usage 
- Fix Sacrificium usage
> [RPR] Arcane Circle fixes

- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/Leasing.cs
- WrathCombo/WrathCombo.cs
> [IPC] Fixed Class-handling

- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
Add Battle target check to Dismantle - Tactician option
> [MCH] Add Battletarget option

- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
- Fix Vicewinder not going off when not in boss instance
- Fix Reawaken not being used when not in boss instance
> [VPR] Fix skill usage

- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
Using Taurenkey's JustUsedOn to help alleviate double Eukrasian Dosis issues (DoT not applying fast enough)
Reported from Discord
> [SGE] Eukrasian Dosis Latency Fix

- WrathCombo/Combos/PvE/ALL/ALL_Config.cs
- WrathCombo/Combos/PvE/ALL/JobActions.cs
- WrathCombo/Combos/PvE/ALL/JobClasses.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
- Fix RPR and some cleanup
- Made `JobActions` and  `JobClasses` use File-scoped namespace
> Fix issues after PR merge

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/GNB/GNB.cs
- WrathCombo/Combos/PvE/GNB/GNB_Config.cs
- WrathCombo/Combos/PvE/GNB/GNB_Helper.cs
- WrathCombo/CustomCombo/WrathOpener.cs
- WrathCombo/Window/Functions/UserConfig.cs
I borked my last PR (oopy), resubmitted & works as intended
> [GNB] Adjusted Opener option to support Lv90 and Lv100 openers

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
Added options for the buffs section to add specific buffs instead of all buffs. 
Inserted code to help mitigate the performance issues this will cause if someone only selects some buffs and not others.
> [BRD] Buffs as seperate options

- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
> [MCH] Fix 1-2-3 after Hypercharge

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- Discord request https://discord.com/channels/1001823907193552978/1355294314267148388
> [SAM] add Senei - Guren standalone option

- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
> [RPR] Fix opener

- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
- Add PB combo in helper class
- make it used for ST and AoE
> [MNK] Optimize PB combo

- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
- optimize for double mirage under buffs
> [DRG] Mirage Dive optimization

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
- WrathCombo/Combos/PvE/VPR/VPR_Config.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
- Cleanup
- Move Reawaken combo to Helper class
- Add bosscheck Awaken
- Split Generation and Legacies ST
- Add Legacy option ST
- Closes #455
> [VRP] Various

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- WrathCombo/Combos/PvE/PCT/PCT_Config.cs
- WrathCombo/Combos/PvE/SMN/SMN_Config.cs
- WrathCombo/Combos/PvP/BLMPVP.cs
- WrathCombo/Combos/PvP/PCTPVP.cs
- WrathCombo/Combos/PvP/RDMPVP.cs
- WrathCombo/Combos/PvP/SMNPvP.cs
- WrathCombo/Window/Functions/Presets.cs
Added Phantom dart to rdm, smn, and pct
Added phantom dart health slider  to all 4 casters
Moved pvp config from the class config file to the pvp like all the others.
> [PVP][Casters] PVP role action and move pvp config to pvp  file

- WrathCombo/AutoRotation/AutoRotationController.cs
> [AutoRot] null checks....I hope

- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
* We don't set the Adv boolean anymore.
> [Healer] Fix DOT threshold

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
Set up/Added Sub options to the dot section to allow more freedom of choice in ST advanced. 
IronJaws refresh
Dot Application outside of opener
Raging Jaws refresh
> [BRD] Dot Application Option

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/Combos/PvE/WHM/WHM_Config.cs
- WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
- docs/CODEOWNERS
> [WHM] Cleanup, Added Default config values

- WrathCombo/Combos/PvE/WHM/WHM.cs
Almost all of the code indentation changes cause warnings
> [WHM] Revert indentation changes

- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/Combos/PvE/WHM/WHM_Config.cs
- WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
Rewrote white mage dot in the bard style copying the purple blue setup given to me a while back
Tested on dummy, 4 man ifrit, and ultima. all 3 dots work, and reapply correctly. hp threshold code remands untouched.
> [WHM] Dot spamming fix

- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Config.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Config.cs
- WrathCombo/Combos/PvE/RPR/RPR_Config.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- WrathCombo/Combos/PvE/VPR/VPR_Helper.cs
- docs/CODEOWNERS
- General cleanup after the status merge
- Added better fires reply for MNK
- Add me as sole owner for SAM
> [Various] Cleanup after merge

- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
- WrathCombo/Combos/PvE/DOL/DOL.cs
- WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvP/ASTPVP.cs
- WrathCombo/Combos/PvP/BLMPVP.cs
- WrathCombo/Combos/PvP/BRDPVP.cs
- WrathCombo/Combos/PvP/DRGPVP.cs
- WrathCombo/Combos/PvP/PCTPVP.cs
- WrathCombo/Combos/PvP/RDMPVP.cs
- WrathCombo/Combos/PvP/SCHPVP.cs
- WrathCombo/Combos/PvP/SMNPvP.cs
- WrathCombo/Combos/PvP/VPRPVP.cs
- WrathCombo/Combos/PvP/WHMPVP.cs
- WrathCombo/CustomCombo/Functions/PlayerCharacter.cs
- WrathCombo/CustomCombo/Functions/Target.cs
- WrathCombo/Window/Tabs/Debug.cs
¯ \ _ (ツ) _ / ¯
Fixed SCH checking for SGE shields
Fixed DeploymentTactics
> [Core] Status Update stragglers/merge issues

- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/AST/AST_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
> [Healers] DoT Refresh is now completely relying on slider.

- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
Makes the check with senei instead of ikishoten, since u use it ALWAYS during meikyo
> [SAM] Better meikyo usage

- WrathCombo/Combos/PvE/ALL/Roles/RoleActions.cs
Fixed HeadGraze from IsOffCooldown to ActionReady
> [PhysRanged] HeadGraze ActionReady'd

- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
Changed Taurens simple st fix to delayed weave. 
Applied same logic to aoe and the advanced as well. Had a bool in the helper that wasnt working with new simplified headgraze code.
> [BRD] Interupt Fix

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SMN/SMN.cs
- WrathCombo/Combos/PvE/SMN/SMN_Config.cs
- WrathCombo/Combos/PvE/SMN/SMN_Helper.cs
> [SMN] Priority selection for Summon Order

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
> [DRG] Lifesurge fix

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/CustomCombo/WrathOpener.cs
- Copy advanced to simple
- Add mp check paradox
- Make paradox use originalhook
- Update Amplifier usage and check
- Add Polyglot usage until raid buff checks ( Added TODO)
- Add more logical triplecase usage
- Update Thunder check
- Add Manaward option
- Add scathe movement for low lvl
> [BLM] cleanup + MP check

- WrathCombo/Combos/PvE/PLD/PLD.cs
- Fixes `Fight or Flight` misbehaving at lower levels.
> [PLD] Operator Precedence Fix

- WrathCombo/Combos/PvE/BLM/BLM.cs
should more closely follow this
- Closes #555
> [BLM] Refine AoE for lower lvl

- WrathCombo/DebugFile.cs
- WrathCombo/Window/Tabs/Settings.cs
> [UI] Suppress queue refinement

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- Add Sencount to SAM opener
- Add `Use ASAP` option to polyglot usage
> [BLM] & [SAM] 

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/WAR/WAR.cs
- WrathCombo/Combos/PvE/WAR/WAR_Config.cs
I may either rewrite `WAR_InfuriateFellCleave` or just delete it altogether in the future, but for now I will just add a conflict warning.
> [WAR] `Fell Cleave Features`

- WrathCombo/WrathCombo.cs
> [Core] Don't Save Debug Configs

- WrathCombo/Window/Tabs/Debug.cs
- Added all `Phantom Actions`.
- Added a few missing PvP actions.
- Refactored `ActionSheet` to display actions based on what category they belong to.
> [UI] ActionReady and ActionSheet Debug Updates

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/PLD/PLD.cs
Just a quick fix cause I was bored. Obviously if you wanna do your own shit @Kaeris-Tempest I can close this
> [PLD] Shield bash spam fix

- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/DRG/DRG_Helper.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/RPR/RPR_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
Add `CanApplyStatus` to BLM, DRG, MCH, RPR and SAM.
> [Various] Status update

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/ALL/ALL.cs
> [Healers] Add Esuna Retargeting Feature

- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/MCH/MCH.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
- WrathCombo/Combos/PvE/RPR/RPR.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/VPR/VPR.cs
DRG:
- Mirage dive fixes
- Cleanup of unneeded originalhook checks
- split jump/high jump so its easier to maintain
- cleanup of AoE for jumps and dives
- Fixes #628 
- Fixes #638 
- Removed Bosschecks in Simple Mode
MNK:
- Force `Riddle of Fire` to weave together with `Brotherhood`
- Removed Bosschecks in Simple Mode
RPR;
- Removed Bosschecks in Simple Mode
VPR:
- Removed Bosschecks in Simple Mode
> [Jobs] Weekly stuffs

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
- WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
> [SGE] some updates

- WrathCombo/CustomCombo/Functions/Status.cs
- WrathCombo/Data/StatusCache.cs
> [Core] Occult Crescent: Dispel more

- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/CustomCombo/Functions/Target.cs
- WrathCombo/Extensions/GameObjectExtensions.cs
- WrathCombo/Window/Tabs/Debug.cs
- Significant streamlining across most functions. Functionality unchanged.
- `InMeleeRange` refactored to avoid type promotion; now scales correctly during PvP.
- `GetTargetDistance` `GetTargetHeightDifference` now use references; logic streamlined.
- `GetTargetHPPercent` now avoids clamping unless necessary; calculation precision improved.
- `TargetIsCasting` `CanInterruptEnemy` early exit conditions streamlined; calculations simplified.
- `NumberOfEnemiesInRange` sheet lookup speed improved; no longer throws on invalid IDs.
- `CanCircleAoe` `CanRangedCircleAoe` `CanConeAoe` `CanLineAoe` filtering streamlined; sheet lookup speed improved.
- `IsInLineOfSight` now performs all calculations as a Dalamud object; calculations simplified.
- New `GetTargetMaxHP` `GetTargetCurrentHP` …
> [Target] Class Revision, Logic Streamlining

- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
SGE
- SGE_ST_DPS: Combined actionID check and replacedActions creation a single property, DosisActions
- SGE_Eukrasia typecast to Value edit
- Combined DosisList and DosisToEDosisList using touple SCH
- SCH_Recitation: Changed switch statement to expression, typecast to Value edit
> [SGE/SCH] Dash of cleanups

- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/CustomCombo/Functions/Party.cs
Fixes the following compiler messages:
> [Core] Squash Errors/Warnings

- WrathCombo/Combos/PvE/SGE/SGE.cs
- resolve build error
- move status check
> [SGE] Mergefix

- WrathCombo/Combos/PvE/DRK/DRK_ActionLogic.cs
> [DRK] Use TBN in Simple Modes

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/BLM/BLM_Config.cs
- Add triplecast suboptions to use always or not when having leylines
> [BLM] make triplecast suboptions

- WrathCombo/Services/IPC/Provider.cs
- WrathCombo/Window/Tabs/Settings.cs
- docs/IPC.md
- docs/IPCExample.cs
- docs/IPCExample.lua
(with Jaksuhn/SomethingNeedDoing#55 getting Wrath in SND to a functional state)
> [Docs] Once-over for all IPC documentation, add SND example

- WrathCombo/Services/IPC/Helper.cs
- WrathCombo/Services/IPC/Provider.cs
> [IPC] Prevent network checks from being problematic

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
> [SGE] Add Standalone retargetted healing options

- WrathCombo/Combos/PvE/DNC/DNC.cs
- WrathCombo/Combos/PvE/DNC/DNC_Config.cs
- WrathCombo/Combos/PvE/DNC/DNC_Helper.cs
> [DNC] Fix Custom Steps

- WrathCombo/Combos/PvE/SMN/SMN.cs
> [SMN] Cyclone strike fix

- WrathCombo/Attributes/RetargetedAttribute.cs
- WrathCombo/AutoRotation/AutoRotationConfig.cs
- WrathCombo/AutoRotation/AutoRotationConfigIPCWrapper.cs
- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/AST/AST_Config.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Config.cs
- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Config.cs
- WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/Combos/PvE/WHM/WHM_Config.cs
- WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
- WrathCombo/Services/IPC/Enums.cs
- WrathCombo/Services/IPC/ProvideAutoRotConfig.cs
- WrathCombo/Window/Tabs/AutoRotationTab.cs
- docs/CODEOWNERS
AST
- !New Feature Movement Option DoT refresh (Checks for Lightspeed)
- !New Feature Re-targeting Standalone for all your re-targeting needs
- !New Feature Single Target Mitigation Combo on Exaltation
- !New Feature AoE Mitigation Combo on Collective Unconscious
- General Code Cleanup
WHM
- Verbage fixes
- General Code Cleanup
- Added Not on Bosses option to Aquaveil
SGE
- !New Feature Re-targeting Standalone for all your re-targeting needs
- !New Feature Single Target Mitigation Combo on Krasis
- !New Feature AoE Mitigation Combo on Holos
- Simple dps Combos
- General Code Cleanup
SCH
- !New Feature Re-targeting Standalone for all your re-targeting needs
- !New Feature Single Target Mitigation Combo on Protraction 
- !New Feature AoE Mitigation Combo on Sacred Soil
- General Code …
> [Healers] Various Additions and Fixes

- WrathCombo/CustomCombo/Functions/Status.cs
- WrathCombo/CustomCombo/Functions/Target.cs
> [Core] Fix CTD in `TargetIsInvincible`

- WrathCombo/CustomCombo/Functions/Status.cs
see title
all bosses come with the same assignment every time. Healers SEEM to always be alpha and tanks beta, and dps is either gamma or delta. 
added hellmaker priority when it lights your floor on fire as a dps
> [Core] Meso Terminal Second Boss Invulnerable check

- WrathCombo/AutoRotation/AutoRotationController.cs
> [7.3 AutoRot] Heal AoE Range increased to 20

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/BRD/BRD.cs
- WrathCombo/Combos/PvE/BRD/BRD_Config.cs
- WrathCombo/Combos/PvE/BRD/BRD_Helper.cs
- WrathCombo/CustomCombo/SimpleTarget.cs
- WrathCombo/Extensions/UIntExtensions.cs
- docs/BurstHoldingMacros.md
- New Feature: Bard Multidotting. Both ST and AoE up to 3 targets as more is a dps loss
- Configs for buffs and dots have changed.
- Updated Burst Hold doc with new macro to turn off buffs.
> [BRD] Multidotting

- WrathCombo/Combos/CustomComboPreset.cs
> [WHM] Fix `ReplacedSkill`

- WrathCombo/AutoRotation/AutoRotationController.cs
- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/NIN/NIN.cs
- WrathCombo/Combos/PvE/NIN/NIN_Config.cs
- WrathCombo/Combos/PvE/NIN/NIN_Helper.cs
- WrathCombo/Data/ActionWatching.cs
- WrathCombo/WrathCombo.cs
- docs/BurstHoldingMacros.md
- docs/CODEOWNERS
- Overhaul of Ninja. ST and AoE
- Many features Added, Adjusted, or Removed. Settings have been reset.
- Expanded on the Hide Standalone. Instant Toggling Hidden off Option.
- ! In Testing, learned that if you are getting manual press mudra fails, the reason is likely the action queue. One can use Reaction to lower the Action Queue from .5, to buy a tenth of a second or so allowing wrath to do its thing without any major affect on gameplay.
https://xivanalysis.com/fflogs/7jTGKgMFXc4Jt8NB/52/2
13 min parse. Zero suggestions.
> [NIN] Gonna be the Hokage

- WrathCombo/Combos/PvE/AST/AST_Helper.cs
> [Core] Fix `AST.JobID` check

- WrathCombo/Combos/PvE/ALL/ALL.cs
> Removed Sprint/Island Sprint actions from ALL

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/ALL/ALL.cs
- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/AST/AST_Helper.cs
- WrathCombo/Combos/PvE/SCH/SCH.cs
- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- WrathCombo/Combos/PvE/SGE/SGE.cs
- WrathCombo/Combos/PvE/SGE/SGE_Helper.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/CustomCombo/Functions/Status.cs
- WrathCombo/Extensions/GameObjectExtensions.cs
- docs/CODEOWNERS
- Added simple Healing for WHM
- Added simple Healing for SCH
- Added simple Healing for SGE
- Added simple healing for AST
- Zbee added GetRole for checking healtargets role
- Added Invincible for the 90% reduction buff, sunken temple of qarn
> [Healers] So Simple a Caveman could do it

- WrathCombo/Commands.cs
> [Core] Fix `/wrath auto target` Command

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/DRG/DRG_Config.cs
- fix AoE
- Add option for one button basic combo
- Cleanup
> [DRG] little fixes

- WrathCombo/Combos/PvE/SAM/SAM.cs
- Fix Yukikazi standalone option to respect the checkboxes
- Refactor ST and AoE basic combo usage
> [SAM] Standalone and AoE

- WrathCombo/Combos/PvE/SCH/SCH_Helper.cs
- Fixed Scholar Dot slider. had the wrong config option
> [SCH] Dot Slider fix

- WrathCombo/Combos/PvE/BLM/BLM.cs
- WrathCombo/Combos/PvE/BLM/BLM_Helper.cs
- Fix fire 1 to despair
- Fix aoe dot usage for pre 58.
> [BLM] fix fire 1 to despair

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Config.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- Fixes the getting stuck on Fuko/Fuga when u got sens
- Fix Simple mode getting stuck
- Add incombat check for MNK buffs
- Add Riddle of Earth + Earth's rumination raidwide option
- Add Mantra raidwide option
- Fixes #802
> [SAM] + [MNK] fix getting stuck 

- WrathCombo/CustomCombo/Functions/Status.cs
- WrathCombo/Window/Tabs/Debug.cs
Dog, Tree, Tentacle bosses
Also fixed code tabbing in Debug
> [AutoRot] Invincible Void Ark Boss Support

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/DRG/DRG.cs
- WrathCombo/Combos/PvE/SAM/SAM.cs
- WrathCombo/Combos/PvE/SAM/SAM_Config.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- Add Ikishoten option to Shinten and Kyuten standalone option
- Some bugfixes for burst pooling
- Remove ranged option DRG AoE Simple mode ( fixes #819 )
> [SAM] Standalone updates

- WrathCombo/CustomCombo/Functions/Status.cs
- WrathCombo/Data/StatusCache.cs
Added:
Disengage when using Heavenly Shield Duty Action in Orbonne Monastary
Heart of the Creator's Plasma Shield Invincibility if attacked from wrong direction.
Fixed a split second moment where AutoRot didn't think Allagan Bomb was invincible
> [AutoRot] Invincibles / Disengages

- WrathCombo/Combos/PvE/AST/AST.cs
- WrathCombo/Combos/PvE/WHM/WHM.cs
- WrathCombo/Combos/PvE/WHM/WHM_Config.cs
- WrathCombo/Combos/PvE/WHM/WHM_Helper.cs
- WrathCombo/Combos/PvP/SGEPVP.cs
- Added Range Check to DPS Assize to prevent waste
- Added Slider to choose overcap window for lilies with  Afflatus Rapture. 
- Added Play 1 Level check due to SE hidden card bug
- Swap last spell to combo action for sage pvp so it cant be broken by manual inputs
> [Various] Little fixes

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/Content/OccultCrescent/OccultCrescent.cs
- WrathCombo/Combos/PvE/PCT/PCT_Helper.cs
- Added debuff check for OC Cannoneer Silver Cannon
- Fixed lvl 90 pct openers
> [Various]  Little Stuff

- WrathCombo/Combos/CustomComboPreset.cs
- WrathCombo/Combos/PvE/MCH/MCH_Helper.cs
- WrathCombo/Combos/PvE/SAM/SAM_Helper.cs
- Fix ikishoten use at 2nd gcd
- Fix ranged option not going off when no suboption selected
- Fix ranged option going off when out of suboption range
- Fix namikiri usage
- Adds lvl 70/80/90 Openers
- closes #831
> [SAM] various fixes

- WrathCombo/Combos/PvE/MNK/MNK.cs
- WrathCombo/Combos/PvE/MNK/MNK_Helper.cs
mostly cleanup and making little tweaks so it aligns better for burst windows
> [MNK] Unifying stuffs + number tweaks
